apiVersion: v1
kind: Service
metadata:
  name: rafeeq-api
  namespace: rafeeq
  labels:
    app: rafeeq
    component: api
spec:
  type: ClusterIP
  selector:
    app: rafeeq
    component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rafeeq-redis
  namespace: rafeeq
  labels:
    app: rafeeq
    component: redis
spec:
  type: ClusterIP
  selector:
    app: rafeeq
    component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
