apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rafeeq.name" . }}-config
  labels:
    {{- include "rafeeq.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
