apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rafeeq.name" . }}-secrets
  labels:
    {{- include "rafeeq.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
